CREATE TABLE `fx`.`currency` (
  `code` VARCHAR(3) NOT NULL,
  `name` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`code`));

CREATE TABLE `fx`.`exchange_rate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `base` VARCHAR(3) NOT NULL,
  `quote` VARCHAR(3) NOT NULL,
  `timestamp` INT NOT NULL,
  `rate` FLOAT NOT NULL,
  PRIMARY KEY (`id`));

  

INSERT INTO currency VALUES ('AED', 'UAE Dirham');
INSERT INTO currency VALUES ('AFN', 'Afghanistan Afghani');
INSERT INTO currency VALUES ('ALL', 'Albanian Lek');
INSERT INTO currency VALUES ('AMD', 'Armenian Dram');
INSERT INTO currency VALUES ('ANG', 'Antilles Guilder');
INSERT INTO currency VALUES ('ARS', 'Argentinian Peso');
INSERT INTO currency VALUES ('AUD', 'Australian Dollar');
INSERT INTO currency VALUES ('AZN', 'Azerbaijani Manat');
INSERT INTO currency VALUES ('BAM', 'Bosnia Herzegovina Mark');
INSERT INTO currency VALUES ('BBD', 'Barbadian Dollar');
INSERT INTO currency VALUES ('BDT', 'Bangladeshi Taka');
INSERT INTO currency VALUES ('BGN', 'Bulgarian Lev');
INSERT INTO currency VALUES ('BHD', 'Baharain Dinar');
INSERT INTO currency VALUES ('BIF', 'Burundian Franc');
INSERT INTO currency VALUES ('BND', 'Brunei Dollar');
INSERT INTO currency VALUES ('BOB', 'Bolivian Boliviano');
INSERT INTO currency VALUES ('BRL', 'Brazil Real');
INSERT INTO currency VALUES ('BSD', 'Bahamas Dollar');
INSERT INTO currency VALUES ('BTC', 'Bitcoin');
INSERT INTO currency VALUES ('BWP', 'Botswana Pula');
INSERT INTO currency VALUES ('BYN', 'Belarusian Ruble');
INSERT INTO currency VALUES ('BZD', 'Belize Dollar');
INSERT INTO currency VALUES ('CAD', 'Canadian Dollar');
INSERT INTO currency VALUES ('CHF', 'Swiss Franc');
INSERT INTO currency VALUES ('CLP', 'Chilean Peso');
INSERT INTO currency VALUES ('CNH', 'Chinese Yuan Offshore');
INSERT INTO currency VALUES ('CNY', 'Chinese Yuan');
INSERT INTO currency VALUES ('COP', 'Colombian Peso');
INSERT INTO currency VALUES ('CRC', 'Costa Rican Colon');
INSERT INTO currency VALUES ('CUP', 'Cuban Peso');
INSERT INTO currency VALUES ('CVE', 'Cape Verdean Escudo');
INSERT INTO currency VALUES ('CZK', 'Czech Koruna');
INSERT INTO currency VALUES ('DJF', 'Djiboutian Franc');
INSERT INTO currency VALUES ('DKK', 'Danish Krone');
INSERT INTO currency VALUES ('DOP', 'Dominican Peso');
INSERT INTO currency VALUES ('DZD', 'Algerian Dinar');
INSERT INTO currency VALUES ('EGP', 'Egyptian Pound');
INSERT INTO currency VALUES ('ETB', 'Ethiopian Birr');
INSERT INTO currency VALUES ('EUR', 'Euro');
INSERT INTO currency VALUES ('FJD', 'Fiji Dollar');
INSERT INTO currency VALUES ('GBP', 'British Pound');
INSERT INTO currency VALUES ('GEL', 'Georgian lari');
INSERT INTO currency VALUES ('GHS', 'Ghanaian Cedi');
INSERT INTO currency VALUES ('GMD', 'Gambian Dalasi');
INSERT INTO currency VALUES ('GNF', 'Guinean Franc');
INSERT INTO currency VALUES ('GTQ', 'Guatemalan Quetzal');
INSERT INTO currency VALUES ('HKD', 'Hong Kong Dollar');
INSERT INTO currency VALUES ('HNL', 'Honduran Lempira');
INSERT INTO currency VALUES ('HRK', 'Croatian Kuna');
INSERT INTO currency VALUES ('HTG', 'Haitian Gourde');
INSERT INTO currency VALUES ('HUF', 'Hungarian Forint');
INSERT INTO currency VALUES ('IDR', 'Indonesian Rupiah');
INSERT INTO currency VALUES ('ILS', 'Israeli Shekel');
INSERT INTO currency VALUES ('INR', 'Indian Rupee');
INSERT INTO currency VALUES ('IQD', 'Iraqi Dinar');
INSERT INTO currency VALUES ('IRR', 'Iranian Rial');
INSERT INTO currency VALUES ('ISK', 'Icelandic Kr');
INSERT INTO currency VALUES ('JMD', 'Jamaican Dollar');
INSERT INTO currency VALUES ('JOD', 'Jordan Dinar');
INSERT INTO currency VALUES ('JPY', 'Japanese Yen');
INSERT INTO currency VALUES ('KES', 'Kenyan Shilling');
INSERT INTO currency VALUES ('KGS', 'Kyrgyzstan som');
INSERT INTO currency VALUES ('KHR', 'Cambodian Riel');
INSERT INTO currency VALUES ('KMF', 'Comorian Franc');
INSERT INTO currency VALUES ('KRW', 'Korean Won');
INSERT INTO currency VALUES ('KWD', 'Kuwaiti Dinar');
INSERT INTO currency VALUES ('KYD', 'Cayman Islands Dollar');
INSERT INTO currency VALUES ('KZT', 'Kazakh Tenge');
INSERT INTO currency VALUES ('LAK', 'Lao Kip');
INSERT INTO currency VALUES ('LBP', 'Lebanese Pound');
INSERT INTO currency VALUES ('LKR', 'Sri Lankan Rupee');
INSERT INTO currency VALUES ('LSL', 'Lesotho loti');
INSERT INTO currency VALUES ('LTC', 'Litecoin');
INSERT INTO currency VALUES ('LTL', 'Lithuanian Litas');
INSERT INTO currency VALUES ('LYD', 'Libyan Dinar');
INSERT INTO currency VALUES ('MAD', 'Moroccan Dirham');
INSERT INTO currency VALUES ('MDL', 'Moldovan Leu');
INSERT INTO currency VALUES ('MGA', 'Malagasy Ariary');
INSERT INTO currency VALUES ('MKD', 'Macedonian Denar');
INSERT INTO currency VALUES ('MMK', 'Myanmar kyat');
INSERT INTO currency VALUES ('MOP', 'Macanese Pataca');
INSERT INTO currency VALUES ('MRO', 'Mauritanian ouguiya');
INSERT INTO currency VALUES ('MUR', 'Mauritian Rupee');
INSERT INTO currency VALUES ('MVR', 'Maldivian Rufiyaa');
INSERT INTO currency VALUES ('MWK', 'Malawian Kwacha');
INSERT INTO currency VALUES ('MXN', 'Mexican Peso');
INSERT INTO currency VALUES ('MYR', 'Malaysian Ringgit');
INSERT INTO currency VALUES ('MZN', 'Mozambican Metical');
INSERT INTO currency VALUES ('NAD', 'Namibian Dollar');
INSERT INTO currency VALUES ('NGN', 'Nigerian Naira');
INSERT INTO currency VALUES ('NIO', 'Nicaraguan Córdoba');
INSERT INTO currency VALUES ('NOK', 'Norwegian Krone');
INSERT INTO currency VALUES ('NPR', 'Nepalese Rupee');
INSERT INTO currency VALUES ('NZD', 'New Zealand Dollar');
INSERT INTO currency VALUES ('OMR', 'Omani Rial');
INSERT INTO currency VALUES ('PAB', 'Panamanian Balboa');
INSERT INTO currency VALUES ('PEN', 'Peru Sol');
INSERT INTO currency VALUES ('PGK', 'Papua New Guinean Kina');
INSERT INTO currency VALUES ('PHP', 'Philippine Peso');
INSERT INTO currency VALUES ('PKR', 'Pakistani Rupee');
INSERT INTO currency VALUES ('PLN', 'Polish Zloty');
INSERT INTO currency VALUES ('PYG', 'Paraguayan Guarani');
INSERT INTO currency VALUES ('QAR', 'Qatari Riyal');
INSERT INTO currency VALUES ('RON', 'Romanian Leu');
INSERT INTO currency VALUES ('RSD', 'Serbian Dinar');
INSERT INTO currency VALUES ('RUB', 'Russian Ruble');
INSERT INTO currency VALUES ('RWF', 'Rwandan Franc');
INSERT INTO currency VALUES ('SAR', 'Saudi Riyal');
INSERT INTO currency VALUES ('SCR', 'Seychelles Rupee');
INSERT INTO currency VALUES ('SDG', 'Sudanese Pound');
INSERT INTO currency VALUES ('SEK', 'Swedish Krona');
INSERT INTO currency VALUES ('SGD', 'Singapore Dollar');
INSERT INTO currency VALUES ('SOS', 'Somali Shilling');
INSERT INTO currency VALUES ('STD', 'São Tomé/Príncipe Dobra');
INSERT INTO currency VALUES ('SVC', 'El Salvador Colon');
INSERT INTO currency VALUES ('SYP', 'Syrian Pound');
INSERT INTO currency VALUES ('SZL', 'Swazi Lilangeni');
INSERT INTO currency VALUES ('THB', 'Thai Baht');
INSERT INTO currency VALUES ('TJS', 'Tajikistani somoni');
INSERT INTO currency VALUES ('TND', 'Tunisian Dinar');
INSERT INTO currency VALUES ('TRY', 'Turkish Lira');
INSERT INTO currency VALUES ('TTD', 'Trinidad Dollar');
INSERT INTO currency VALUES ('TWD', 'Taiwan Dollar');
INSERT INTO currency VALUES ('TZS', 'Tanzanian Shilling');
INSERT INTO currency VALUES ('UAH', 'Ukrainian Hryvnia');
INSERT INTO currency VALUES ('UGX', 'Ugandan Shilling');
INSERT INTO currency VALUES ('USD', 'US Dollar');
INSERT INTO currency VALUES ('UYU', 'Uruguayan Peso');
INSERT INTO currency VALUES ('UZS', 'Uzbekistani Sum');
INSERT INTO currency VALUES ('VEF', 'Venezuelan Bolivar');
INSERT INTO currency VALUES ('VND', 'Vietnamese Dong');
INSERT INTO currency VALUES ('VUV', 'Vanuatu vatu');
INSERT INTO currency VALUES ('XAF', 'Central African Franc');
INSERT INTO currency VALUES ('XCD', 'East Caribbean Dollar');
INSERT INTO currency VALUES ('XOF', 'West African CFA franc');
INSERT INTO currency VALUES ('XPF', 'French Pacific Franc');
INSERT INTO currency VALUES ('YER', 'Yemeni Rial');
INSERT INTO currency VALUES ('ZAR', 'South African Rand');
INSERT INTO currency VALUES ('ZMK', 'Zambia Kwacha');